---
title: "Polyfold Gromov--Witten theory"
sidebar: false
bibliography: references.bib
link-citations: true
html-math-method:
  method: mathjax
---

::: {.hidden}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Standard Commands %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%mathbb
\newcommand{\N}{{\mathbb N}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\Z}{{\mathbb Z}}
\newcommand{\B}{{\mathbb B}}
\newcommand{\C}{{\mathbb C}}
\newcommand{\E}{{\mathbb E}}
\newcommand{\F}{{\mathbb F}}
\newcommand{\G}{{\mathbb G}}
\newcommand{\W}{{\mathbb W}}
\newcommand{\Q}{{\mathbb Q}}
\renewcommand{\H}{{\mathbb H}}
\newcommand{\T}{{\mathbb T}}

%greek
\newcommand{\p}{\phi}
\newcommand{\ph}{\varphi}
\renewcommand{\a}{\alpha}
\renewcommand{\b}{\beta}
\newcommand{\de}{\delta}
\renewcommand{\k}{\kappa}
\newcommand{\ep}{\varepsilon}
\newcommand{\eps}{\epsilon}
\newcommand{\s}{\sigma}
\newcommand{\e}{\eta}
\newcommand{\g}{\gamma}
\renewcommand{\th}{\theta}
\renewcommand{\r}{\rho}
\renewcommand{\t}{\tau}
\renewcommand{\i}{\iota}
\newcommand{\x}{\xi}
\renewcommand{\c}{\chi}
\newcommand{\n}{\nu}
\newcommand{\m}{\mu}
\newcommand{\z}{\zeta}
\renewcommand{\l}{\lambda}

%GREEK
\newcommand{\De}{\Delta}
\renewcommand{\L}{\Lambda}
\renewcommand{\G}{\Gamma}
\newcommand{\Si}{\Sigma}
\newcommand{\Th}{\Theta}
\newcommand{\X}{\Xi}
\newcommand{\Om}{\Omega}
\renewcommand{\P}{\Phi}

%cal
\newcommand{\cA}{{\mathcal A}}
\newcommand{\cB}{{\mathcal B}}
\newcommand{\cC}{{\mathcal C}}
\newcommand{\cD}{{\mathcal D}}
\newcommand{\cE}{{\mathcal E}}
\newcommand{\cF}{{\mathcal F}}
\newcommand{\cG}{{\mathcal G}}
\newcommand{\cH}{{\mathcal H}}
\newcommand{\cI}{{\mathcal I}}
\newcommand{\cJ}{{\mathcal J}}
\newcommand{\cK}{{\mathcal K}}
\newcommand{\cL}{{\mathcal L}}
\newcommand{\cM}{{\mathcal M}}
\newcommand{\cN}{{\mathcal N}}
\newcommand{\cO}{{\mathcal O}}
\newcommand{\cP}{{\mathcal P}}
\newcommand{\cQ}{{\mathcal Q}}
\newcommand{\cR}{{\mathcal R}}
\newcommand{\cS}{{\mathcal S}}
\newcommand{\cT}{{\mathcal T}}
\newcommand{\cU}{{\mathcal U}}
\newcommand{\cV}{{\mathcal V}}
\newcommand{\cW}{{\mathcal W}}
\newcommand{\cX}{{\mathcal X}}
\newcommand{\cY}{{\mathcal Y}}
\newcommand{\cZ}{{\mathcal Z}}

%tilde
\newcommand{\ta}{{\tilde\alpha}}
\newcommand{\tg}{{\tilde g}}
\newcommand{\tu}{{\tilde u}}
\newcommand{\tw}{{\tilde w}}
\newcommand{\tep}{{\tilde\ep}}
\newcommand{\tx}{{\tilde\x}}
\newcommand{\tA}{{\tilde A}}
\newcommand{\tC}{{\tilde C}}
\newcommand{\tD}{{\tilde D}}
\newcommand{\tM}{{\tilde M}}
\newcommand{\tR}{{\tilde R}}
\newcommand{\tP}{{\tilde\Phi}}
\newcommand{\tU}{{\tilde U}}
\newcommand{\tX}{{\tilde\X}}

%bar
\newcommand{\bc}{{\bar c}}
\newcommand{\br}{{\bar r}}
\newcommand{\bph}{{\bar\p}}
\newcommand{\bp}{{\bar p}}
\newcommand{\bq}{{\bar q}}
\newcommand{\bx}{{\bar x}}
\newcommand{\by}{{\bar y}}
\newcommand{\brh}{{\bar\r}}
%\def\bm{{\bar\m}}
\newcommand{\bep}{{\bar\ep}}
\newcommand{\bt}{{\bar\t}}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Math Commands %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%compactified moduli space
\newcommand{\CM}{\bar{\mathcal{M}}}

% % % % %SYMPLECTIC GEOMETRY % % % % %
\newcommand{\ww}{\omega}
\newcommand{\CP}{\mathbb{C}P}
\newcommand{\delbar}{\bar{\partial}}
\newcommand{\delbarj}{\delbar_J}

\newcommand{\delbarinv}{\smash{\overline{\partial}}\vphantom{\partial}^{-1}}
\newcommand{\delbarjinv}{\smash{\delbarj}\vphantom{\partial}^{-1}}

% % % % %Hat Delbar % % % % %
\newcommand{\hdelbar}{
\mathchoice
{% \displaystyle
\hat{\overline{\partial}}
}
{% \textstyle
\scalerel*{\hat{\overline{\partial}}}{\hat{M}}
}
{}{}
}
\newcommand{\hdelbarj}{
\mathchoice
{% \displaystyle
\hat{\overline{\partial}}\_J
}
{% \textstyle
\scalerel*{\hat{\overline{\partial}}\_J}{\hat{M}\_J}
}
{}{}
}

\newcommand{\hb}{
\mathchoice
{% \displaystyle
B*{\frac{1}{2}}
}
{% \textstyle
B*{1/2}
}
{}{}
}

\newcommand{\abs}[1]{\lvert#1\rvert}
\newcommand{\norm}[1]{\left\Vert#1\right\Vert}

\DeclareMathOperator{\codim}{codim}
\DeclareMathOperator{\rank}{rank}
\DeclareMathOperator{\ind}{ind}
\DeclareMathOperator{\dR}{dR}

% % % % %COLORS % % % % %
\newcommand{\red}[1]{\textcolor{red}{#1}}
\newcommand{\green}[1]{\textcolor{green}{#1}}
\newcommand{\blue}[1]{\textcolor{blue}{#1}}

% % % % %GROMOV-WITTEN LANGUAGE % % % % %
\DeclareMathOperator{\GW}{GW}
\DeclareMathOperator{\PD}{PD}

% % % % %THOM LANGUAGE % % % % %
\newcommand{\Orth}{\text{O}}
\newcommand{\SO}{\text{SO}}

% % % % %POLYFOLD LANGUAGE % % % % %
\newcommand{\ssc}{\text{sc}}
\newcommand{\dmspace}{\bar{\mathcal{M}}}
\newcommand{\dmlog}{\smash{\bar{\mathcal{M}}}\vphantom{\mathcal{M}}^{\text{log}}}
\newcommand{\dmexp}{\smash{\bar{\mathcal{M}}}\vphantom{\mathcal{M}}^{\text{exp}}}
\newcommand{\nspace}{\overline{\mathcal{N}}}
\newcommand{\av}{\text{av}}

\newcommand{\bssc}{\text{Sc}}
\newcommand{\supp}{\operatorname{supp}}
\newcommand{\id}{\operatorname{id}}
\newcommand{\pt}{\operatorname{pt}}
\newcommand{\sign}{\text{sgn}}
\newcommand{\Aut}{\text{Aut}}
\newcommand{\pr}{\operatorname{pr}}
:::

### Notes to self

This documents my mathematical accomplishments over the last decade.
Explain it as such!
Everything in my mathematical life revolved around a proof of the Gromov--Witten axioms.

## History of the Gromov--Witten axioms

In 1985 Gromov published the paper "Pseudo holomorphic curves in symplectic manifolds", laying the foundations for the modern study of pseudo holomorphic curves (also know as $J$-holomorphic curves) in symplectic topology [@G].
In this paper, Gromov proved a compactness result for the moduli space of $J$-holomorphic curves in a fixed homology class. This paper contained antecedents to the modern notion of the Gromov--Witten invariants in the proofs of the nonsqueezing theorem and the uniqueness of symplectic structures on $\CP^2$.

Around 1988, inspired by Floer's study of gauge theory on three manifolds, Witten introduced the topological sigma model [@floer1988instanton; @witten1988topological].
The invariants of this model are the "$k$-point correlation functions", another precursor to the modern notion of the Gromov--Witten invariants.
Witten also observed some of the relationships between these invariants and possible degenerations of Riemann surfaces [@witten1990two].
Further precursors to the notion of the Gromov--Witten invariants can also be seen in McDuff's classification of symplectic ruled surfaces [@mcduff1991symplectic].

In 1993 Ruan gave a modern definition of the genus zero Gromov--Witten invariants for semipositive symplectic manifolds [@ruan1996topological; @ruan1994symplectic]. At the end of 1993, Ruan and Tian established the associativity of the quantum product for semipositive symplectic manifolds, giving a mathematical basis to the composition law of Witten's topological sigma model [@rt1995quatumcohomology].

In 1994 Kontsevich and Manin stated the Gromov--Witten axioms, given as a list of formal relations between the Gromov--Witten invariants [@KM].
At the time it was not possible for Kontsevich and Manin to give a proof of the relations they listed; the definition of the Gromov--Witten invariant (complete with homology classes from a Deligne--Mumford space) would require in addition new ideas involving "stable maps" [@Kstable].
Hence they used to term "axiom" with the presumed meaning "to take for assumption without proof"/ "to use as a premise for further reasoning". And indeed, from these starting assumptions they were able to establish foundational results in enumerative geometry, answers to esoteric questions such as:

> **Kontsevich's recursion formula.** _Let $d\geq 1$. How many degree $d$ rational curves in $\CP^2$ pass through $3d - 1$ points in general position?_

Moreover, in this paper they outlined some of the formal consequences of the axioms by demonstrating how to combine the invariants into a Gromov--Witten potential, and interpret the axioms as differential equations which the potential satisfies.

To varying extents, this work has predated the construction of a well-defined Gromov--Witten invariant in symplectic geometry for $J$-holomorphic curves of arbitrary genus, and for all closed symplectic manifolds.
Efforts to construct a well-defined Gromov--Witten invariant constitute an ever growing list of publications, including but not limited to the following: [@LT; @FO; @fukaya2012technical; @Si; @cieliebak2007symplectic; @mcduff2012smooth; @mcduff2018fundamental; @MWtopology; @ionel2013natural; @pardon2016algebraic].
A discussion of some of the difficulties inherent in these approaches can be found in [@ffgw2016polyfoldsfirstandsecondlook].
Similarly, there have been several efforts to prove the Gromov--Witten axioms [@FO; @MSbook; @castellano2016genus].

Over the past two decades, Hofer, Wysocki, and Zehnder have developed a new approach to resolving transversality issues that arise in the study of $J$-holomorphic curves in symplectic geometry called _polyfold theory_ [@HWZ1; @HWZ2; @HWZ3; @HWZGW; @HWZsc; @HWZdm; @HWZint; @HWZbook]. This approach has been successful in constructing a well-defined Gromov--Witten invariant [@HWZGW].

## What is a Gromov--Witten invariant?

Let $(M,\ww)$ be a closed symplectic manifold of dimension $\dim M = 2n$, and let $J$ be a $\ww$-compatible almost complex structure.
For a fixed homology class $A\in H_2(M,\Z)$, and for fixed integers $g\geq 0$, $k\geq 0$, we consider the set of $J$-holomorphic curves:

$$
	\cM_{A,g,k}(J) :=
	\left\{
	\begin{array}{c}
		u: (\Sigma_g,j) \to M \\
		\{z_1,\ldots,z_k\}\in \Sigma_g
	\end{array}
	\biggm|
	\begin{array}{c}
		\tfrac{1}{2} (du+J\circ du\circ j)=0 \\
		u_*[\Sigma_g] = A
	\end{array}
	\right\}
	\biggm/
	\begin{array}{l}
		u \sim u\circ \phi, \\
		\phi\in \Aut
	\end{array}
$$

consisting of smooth maps $u:(\Sigma_g,j)\to M$ which satisfy the Cauchy--Riemann equation modulo reparametrization; here $(\Sigma_g,j)$ is a genus $g$ Riemann surface and $\Aut$ is the automorphism group of the Riemann surface $(\Sigma_g,j)$ which preserves the ordering of the marked points.

Gromov proved this set has a natural compactification in [@G], which was later refined into the stable map compactification of Kontsevich in [@Kstable], and thus we may also consider its compactification, the **Gromov--Witten moduli space**:

$$
	\CM_{A,g,k} (J) := \cM_{A,g,k} (J) \sqcup \{\text{stable nodal $J$-holomorphic curves}\}.
$$

We seek to use this space to construct invariants of the symplectic manifold $M$.
To this end, we define the **evaluation map** which evaluates a stable curve on each marked point:

$$
	ev: \CM_{A,g,k} (J) \to M\times \cdots \times M.
$$

On the top stratum of non-noded stable $J$-holomorphic curves it is given by

$$
	ev\left([(u,z_1,\ldots,z_k)] \right): = (u(z_1),\ldots, u(z_k)).
$$

With the fixed integers $g \geq 0$, $k \geq 3$ we also consider the associated **Deligne--Mumford space**, the natural compactification of the space of configurations of a complex structure and $k$-marked points on a genus $g$ Riemann surface modulo biholomorphic equivalence:

$$
	\dmspace_{g,k} := \text{cl} \left(\{ j, \{z_1,\ldots,z_k\}\in \Sigma_g \mid j \text{ complex structure on } \Sigma_g, z_i\neq z_j \text{ if } i \neq j\} / \text{Aut} \right).
$$

When $g = 0$ this space is a finite-dimensional manifold, and when $g\neq 0$ this space is a finite-dimensional orbifold, in either case of dimension
$\text{dim}$ $\dmspace_{g,k} = 6g - 6 + 2k$
We may define a **projection map** from the GW-moduli space to the DM-space which forgets the curve which maps to $M$ and which stabilizes the resulting unstable domain components:

$$
	\pi: \CM_{A,g,k} (J) \to \dmspace_{g,k}.
$$

On the top stratum of non-noded stable $J$-holomorphic curves it forgets the map $u$ and is given by

$$
	\pi\left([(u,j,z_1,\ldots,z_k)]\right) := [(j,z_1,\ldots,z_k)].
$$

The traditional interpretation of a **Gromov--Witten invariant** is the (supposedly) finite count of $J$-holomorphic curves which at the $i$th-marked point pass through a submanifold $\cX_i \subset M$ and whose marked point configuration is restricted by the projection map to a suborbifold $\cB \subset \dmspace_{g,k}$.

Such an intersection number should depend only on the homology classes of the submanifolds, and should be independent of the almost complex structure. This count can be packaged algebraically as a homomorphism:

$$
	\GW_{A,g,k} : H_*(M;\Q)^{\otimes k} \times H_*(\dmspace_{g,k};\Q) \to \Q.
$$

A foundational problem in symplectic geometry is to actually show that such a GW-invariant is _well-defined_.
Ideally, we would like to define a GW-invariant rigorously via an intersection number:

$$
 \GW_{A,g,k} ([\cX_1],\ldots,[\cX_k];[\cB]) = (ev\times \pi) (\CM_{A,g,k} (J)) \cdot (\cX_1\times \cdots \times \cX_k \times \cB),
$$

or as an integral:

$$
 \GW_{A,g,k} ([\cX_1],\ldots,[\cX_k];[\cB]) = \int_{\CM_{A,g,k}(J)} ev^* (\PD [\cX_1]\wedge \cdots \wedge \PD [\cX_k]) \wedge \pi^* \PD [\cB],
$$

or as a pairing with a (virtual) fundamental class:

$$
 \GW_{A,g,k} ([\cX_1],\ldots,[\cX_k];[\cB]) = \left\langle (ev\times\pi)_* [\CM_{A,g,k}(J)], \PD [\cX_1\times\cdots\times\cX_k\times\cB] \right\rangle.
$$

Such definitions require additional structure on the GW-moduli space; an intersection number requires tangent spaces and notions of transversal intersection, an integral requires smooth partitions of unity and notions of differential forms, and a (virtual) fundamental class requires a distinguished homology class on the topological space.

However, _a priori_, the GW-moduli space only has the structure of a compact topological space, and this alone is insufficient to define any of the above. More structure is needed.

## The classical pseudocycle Gromov--Witten invariant for genus-zero and semipositive symplectic manifolds

## The polyfold Gromov--Witten invariant for arbitrary genus and general symplectic manifolds

Polyfold theory, developed by Hofer, Wysocki, and Zehnder, is a modern new approach to resolving transversality issues that arise in attempts to solve moduli space problems in symplectic geometry.
The polyfold theoretic approach to solving a moduli space problem is to recast the problem into familiar terms from differential geometry.
To do this, we may construct a "Gromov--Witten polyfold" $\cZ_{A,g,k}$---a massive, infinite-dimensional ambient space, designed to contain the entire unperturbed Gromov--Witten moduli space $\CM_{A,g,k}(J)$ as a compact subset.
We may furthermore construct a "strong polyfold bundle" $\cW_{A,g,k}$ over $\cZ_{A,g,k}$; the Cauchy--Riemann operator then defines a "scale smooth Fredholm section" of this bundle, $\delbarj :\cZ_{A,g,k} \to \cW_{A,g,k}$, such that $\delbarjinv(0) = \CM_{A,g,k}(J)$.
We can construct "abstract perturbations" $p$ of this section such that $\delbarj +p$ is transverse to the zero section and such that $(\delbarj+p)^{-1}(0)$ is a compact set.
In this way, we may take a scale smooth Fredholm section and "regularize" the unperturbed Gromov--Witten moduli space yielding a **perturbed Gromov--Witten moduli space** $\cS_{A,g,k}(p):= (\delbarj+p)^{-1}(0)$ which has the structure of a compact oriented "weighted branched orbifold".

$$
		\begin{array}{c}
		\CM_{A,g,k}(J) = \delbarj^{-1}(0)        \\
		\text{\small{compact topological space}} \\
		\end{array}
		\xrightarrow{\text{"polyfold regularization"}}
		\begin{array}{c}
			\cS_{A,g,k}(p):=(\delbarj+p)^{-1}(0) \\
			\text{\small{compact "weighted branched orbifold"}}
		\end{array}
$$

This approach has been successful in giving a well-defined Gromov--Witten invariant for curves of arbitrary genus, and for all closed symplectic manifolds.
Suppose that $2g+k\geq 3$, and consider the following diagram of smooth maps between the perturbed Gromov--Witten moduli space $\cS_{A,g,k}(p)$, the $k$-fold product manifold $M^k$, and the Deligne--Mumford orbifold $\dmlog_{g,k}$:

$$
	\begin{align*}
		&\cS_{A,g,k}(p) \xrightarrow{ev_1\times\cdots\times ev_k} M^k\\
		&\pi \bigg{\downarrow} \\
		&\dmlog_{g,k}
	\end{align*}
$$

Here $ev_i$ is evaluation at the $i$th-marked point, and $\pi$ is the projection map to the Deligne--Mumford space which forgets the stable map solution and stabilizes the resulting nodal Riemann surface by contracting unstable components.

Consider homology classes $\alpha_1,\ldots, \alpha_k \in H_* (M;\Q)$ and $\beta\in H_* (\dmlog_{g,k};\Q)$.
We can represent the Poincar\'e duals of the $\alpha_i$ and $\beta$ by closed differential forms in the de Rahm cohomology groups, $\PD(\alpha_i)\in H^*_{\dR} (M)$ and $\PD(\beta)\in H^*_{\dR}(\dmlog_{g,k})$.
By pulling back via the evaluation and projection maps, we obtain a closed $\ssc$-smooth differential form

$$
	ev_1^* \PD (\alpha_1) \wedge \cdots \wedge ev_k^* \PD(\alpha_k) \wedge\pi^* \PD (\beta) \in H^*_{\dR} (\cZ_{A,g,k}).
$$

**Theorem.** [@HWZGW, Thm. 1.12]
_The **polyfold Gromov--Witten invariant** is the homomorphism_

$$
		\GW_{A,g,k} : H_* (M;\Q)^{\otimes k} \otimes H_* (\dmlog_{g,k}; \Q) \to \Q
$$

_defined via the "branched integration" of [@HWZint]:_

$$
		\GW_{A,g,k} (\alpha_1,\ldots,\alpha_k;\beta) : = \int_{\cS_{A,g,k}(p)} ev_1^* \PD (\alpha_1) \wedge \cdots \wedge ev_k^* \PD(\alpha_k) \wedge\pi^* \PD (\beta).
$$

_This invariant does not depend on the choice of perturbation._

### References

::: {#refs}
:::
